name: Hello world
on: 
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: hello world
       run: echo "Hello world from github action"
     - name: print take care
       run: echo "take care bro"
